services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5410:5432"

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=postgres@gmail.com'
      - 'PGADMIN_DEFAULT_PASSWORD=admin'
    ports:
      - "5050:80"
    depends_on:
      - postgres


volumes:
  postgres_data:
