# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaProdutos.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class TelaProdutosUi(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(931, 840)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnLogo = QtWidgets.QPushButton(self.centralwidget)
        self.btnLogo.setGeometry(QtCore.QRect(10, 0, 71, 71))
        self.btnLogo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLogo.setStyleSheet("\n"
                                   "QPushButton {  \n"
                                   "    background-color: rgb(0, 75, 63);\n"
                                   "   font: 15pt \"Cooper Black\";\n"
                                   "    color: rgb(255, 255, 255); /* Cor do texto */\n"
                                   "    border-radius: 8px; /* Bordas arredondadas */\n"
                                   "    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
                                   "image:url(:/images/images/logofolha.png)\n"
                                   "    \n"
                                   "       \n"
                                   "}\n"
                                   "\n"
                                   "\n"
                                   "\n"
                                   "\n"
                                   "")
        self.btnLogo.setText("")
        self.btnLogo.setObjectName("btnLogo")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 931, 71))
        self.label_2.setStyleSheet("background-color: rgb(0, 75, 63);\n"
"\n"
"\n"
"                    ")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(360, 90, 230, 41))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0, 670, 931, 161))
        self.label_8.setStyleSheet("background-color: rgb(0, 75, 63);\n"
"\n"
"\n"
"                    ")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")

        self.btnNomelogo = QtWidgets.QPushButton(self.centralwidget)
        self.btnNomelogo.setGeometry(QtCore.QRect(70, 10, 181, 51))
        self.btnNomelogo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNomelogo.setStyleSheet("\n"

                                       "QPushButton {  \n"
                                       "    background-color: rgb(0, 75, 63);\n"
                                       "   font: 15pt \"Cooper Black\";\n"
                                       "    color: rgb(255, 255, 255); /* Cor do texto */\n"
                                       "    border-radius: 8px; /* Bordas arredondadas */\n"
                                       "    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
                                       "    \n"
                                       "       \n"
                                       "}\n"
                                       "\n"
                                       "\n"
                                       "\n"
                                       "\n"
                                       "")
        self.btnNomelogo.setObjectName("btnNomelogo")






        self.botaoCesta = QtWidgets.QPushButton(self.centralwidget)
        self.botaoCesta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaoCesta.setGeometry(QtCore.QRect(670, 20, 91, 38))
        self.botaoCesta.setStyleSheet("QPushButton {\n"
"                        background-color: rgb(0, 75, 63);\n"
"                        font: 75 9pt \"MS Shell Dlg 2\";\n"
"                        color: rgb(255, 255, 255); /* Cor do texto */\n"
"                        border-radius: 8px; /* Bordas arredondadas */\n"
"                        padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
"                        image: url(:/images/images/001-shopping-basket.png); /* Caminho da imagem */\n"
"                        image-position:left;\n"
"                        text-align: right; /* Centraliza o texto */\n"
"                        }\n"
"\n"
"                        QPushButton:hover{\n"
"                        background-color: #E5E5E5;\n"
"                        font: 75 9pt \"MS Shell Dlg 2\";\n"
"                        color: rgb(255, 255, 255); /* Cor do texto */\n"
"                        border-radius: 8px; /* Bordas arredondadas */\n"
"                        padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
"                        image: url(:/images/images/001-shopping-basket.png); /* Caminho da imagem */\n"
"                        image-position:left;\n"
"                        text-align: right; /* Centraliza o texto */\n"
"                        border: 1px solid #CCCCCC;\n"
"                        box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); /* Sombra leve */\n"
"                        }\n"
"                        QPushButton:pressed{\n"
"                        background-color: #E5E5E5;\n"
"                        font: 75 9pt \"MS Shell Dlg 2\";\n"
"                        color: rgb(255, 255, 255); /* Cor do texto */\n"
"                        border-radius: 8px; /* Bordas arredondadas */\n"
"                        padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
"                        image: url(:/images/images/001-shopping-basket.png); /* Caminho da imagem */\n"
"                        image-position:left;\n"
"                        text-align: right; /* Centraliza o texto */\n"
"                        border: 1px solid #CCCCCC;\n"
"                        box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); /* Sombra leve */\n"
"                        background-color: #D6D6D6; /* Fundo mais escuro */\n"
"                        box-shadow: 0px 2px 3px rgba(0, 0, 0, 0.2); /* Menor sombra */\n"
"                        transform: translateY(2px); /* Deslocamento para baixo */\n"
"                        border: 1px solid #AAAAAA; /* Borda mais escura */\n"
"                        }\n"
"\n"
"\n"
"                    ")
        self.botaoCesta.setObjectName("botaoCesta")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(20, 680, 321, 131))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_25 = QtWidgets.QLabel(self.frame_5)
        self.label_25.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_5)
        self.label_26.setGeometry(QtCore.QRect(10, 30, 301, 91))
        self.label_26.setObjectName("label_26")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(420, 680, 181, 131))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_27 = QtWidgets.QLabel(self.frame_6)
        self.label_27.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame_6)
        self.label_28.setGeometry(QtCore.QRect(10, 10, 301, 91))
        self.label_28.setObjectName("label_28")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(710, 680, 171, 131))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_29 = QtWidgets.QLabel(self.frame_7)
        self.label_29.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame_7)
        self.label_30.setGeometry(QtCore.QRect(10, 10, 301, 91))
        self.label_30.setGeometry(QtCore.QRect(10, 20, 301, 91))
        self.label_30.setObjectName("label_30")
        self.botaoGerencia = QtWidgets.QPushButton(self.centralwidget)
        self.botaoGerencia.setCursor((QtGui.QCursor(QtCore.Qt.PointingHandCursor)))
        self.botaoGerencia.setGeometry(QtCore.QRect(780, 20, 111, 38))
        self.botaoGerencia.setStyleSheet("QPushButton {  \n"
                                         "    \n"
                                         "    background-color: rgb(0, 75, 63);\n"
                                         "    font: 75 9pt \"MS Shell Dlg 2\";\n"
                                         "    color: rgb(255, 255, 255); /* Cor do texto */\n"
                                         "    border-radius: 8px; /* Bordas arredondadas */\n"
                                         "    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
                                         "   image: url(:/images/images/gerenciamento-de-projetos.png); /* Caminho da imagem */\n"
                                         "    image-position:left;   \n"
                                         "    text-align: right; /* Centraliza o texto */    \n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:hover{\n"
                                         "  background-color: #E5E5E5;\n"
                                         "    font: 75 9pt \"MS Shell Dlg 2\";\n"
                                         "    color: rgb(255, 255, 255); /* Cor do texto */\n"
                                         "    border-radius: 8px; /* Bordas arredondadas */\n"
                                         "    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
                                         "   image: url(:/images/images/gerenciamento-de-projetos.png); /* Caminho da imagem */\n"
                                         "    image-position:left;   \n"
                                         "    text-align: right; /* Centraliza o texto */\n"
                                         "border: 1px solid #CCCCCC;\n"
                                         "box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); /* Sombra leve */\n"
                                         "}\n"
                                         "QPushButton:pressed{\n"
                                         "background-color: #E5E5E5;\n"
                                         "    font: 75 9pt \"MS Shell Dlg 2\";\n"
                                         "    color: rgb(255, 255, 255); /* Cor do texto */\n"
                                         "    border-radius: 8px; /* Bordas arredondadas */\n"
                                         "    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
                                         "  image: url(:/images/images/gerenciamento-de-projetos.png); /* Caminho da imagem */\n"
                                         "    image-position:left;   \n"
                                         "    text-align: right; /* Centraliza o texto */\n"
                                         "border: 1px solid #CCCCCC;\n"
                                         "box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); /* Sombra leve */\n"
                                         "background-color: #D6D6D6; /* Fundo mais escuro */\n"
                                         "    box-shadow: 0px 2px 3px rgba(0, 0, 0, 0.2); /* Menor sombra */\n"
                                         "    transform: translateY(2px); /* Deslocamento para baixo */\n"
                                         "    border: 1px solid #AAAAAA; /* Borda mais escura */\n"
                                         "}\n"
                                         "\n"
                                         "\n"
                                         "")
        self.botaoGerencia.setObjectName("botaoGerencia")

        self.label_8.raise_()
        self.label_2.raise_()
        self.label_7.raise_()
        self.btnLogo.raise_()
        self.btnNomelogo.raise_()
        self.botaoCesta.raise_()
        self.frame_5.raise_()
        self.frame_6.raise_()
        self.frame_7.raise_()
        self.botaoGerencia.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        # Tabela de produtos
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(80, 150, 800, 480))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)  # Colunas: Produto, Valor, Ação
        self.tableWidget.setRowCount(0)  # Inicialmente sem linhas

        # Ocultando o cabeçalho vertical (numeração das linhas)
        self.tableWidget.verticalHeader().setVisible(False)

        # Ajustando a altura padrão de todas as linhas
        self.tableWidget.verticalHeader().setDefaultSectionSize(50)  # Define a altura de todas as linhas para 50 pixels

        # Definindo o cabeçalho da tabela
        self.tableWidget.setHorizontalHeaderLabels(["Nome", "Preço", "Quantidade", ""])

        # Ajuste das larguras das colunas
        self.tableWidget.setColumnWidth(0, 100)
        self.tableWidget.setColumnWidth(1, 400)  # Coluna de Produto - maior largura
        self.tableWidget.setColumnWidth(2, 150)  # Coluna de Valor - largura menor
        self.tableWidget.setColumnWidth(3, 150)  # Coluna de Ação (Botão) - mesma largura que a de Valor

        # Removendo a linha das colunas e as bordas das células
        self.tableWidget.setStyleSheet("""
                           QTableWidget {
                               background-color: white;
                               border: none;
                           }
                           QTableWidget::item {
                               border-bottom: 1px solid lightgray;
                               padding: 10px;
                           }
                           QHeaderView::section {
                               background-color: white;
                               border: none;
                               padding: 10px;
                               font-weight: bold;
                               color: #004b3f;
                           }
                           QTableWidget::horizontalHeader {
                               border: none;
                           }
                           QTableWidget::verticalHeader {
                               border: none;
                           }
                           QTableWidget::item:selected {
                               background-color: #e6f7f1; /* Cor de fundo ao selecionar */
                           }
                       """)

        # Exibindo o conteúdo da janela
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        MainWindow.setStatusBar(self.statusbar)



        # Criando um botão na coluna "Ação" (coluna 3)
        button = QtWidgets.QPushButton("Adicionar à cesta")
        button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))  # Cursor de mão ao passar sobre o botão
        button.setStyleSheet("""
                           QPushButton {
                               background-color: rgb(0, 75, 63);
                               font: 75 7pt "MS Shell Dlg 2";
                               color: rgb(255, 255, 255); /* Cor do texto */
                               border-radius: 8px; /* Bordas arredondadas */
                               padding: 10px; /* Padding interno */
                               image: url(:/images/images/001-shopping-basket.png); /* Caminho da imagem */
                               image-position:left;
                               text-align: right; /* Centraliza o texto */
                           }
                           QPushButton:hover {
                               background-color: #E5E5E5;
                               font: 75 7pt "MS Shell Dlg 2";
                               color: rgb(255, 255, 255); /* Cor do texto */
                               border-radius: 8px;
                               padding: 10px;
                               image: url(:/images/images/001-shopping-basket.png);
                               image-position:left;
                               text-align: right;
                               border: 1px solid #CCCCCC;
                               box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); /* Sombra leve */
                           }
                           QPushButton:pressed {
                               background-color: #D6D6D6;
                               font: 75 7pt "MS Shell Dlg 2";
                               color: rgb(255, 255, 255); /* Cor do texto */
                               border-radius: 8px;
                               padding: 10px;
                               image: url(:/images/images/001-shopping-basket.png);
                               image-position:left;
                               text-align: right;
                               border: 1px solid #CCCCCC;
                               box-shadow: 0px 2px 3px rgba(0, 0, 0, 0.2); /* Menor sombra */
                           }
                       """)



        # Exibindo o conteúdo da janela
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        MainWindow.setStatusBar(self.statusbar)
        # Adicionando um exemplo de produto à tabela
        self.tableWidget.insertRow(0)  # Insere uma nova linha na tabela
        self.tableWidget.setItem(0, 0, QtWidgets.QTableWidgetItem("001"))  # ID do produto
        self.tableWidget.setItem(0, 1, QtWidgets.QTableWidgetItem("Produto Exemplo"))  # Nome do produto
        self.tableWidget.setItem(0, 2, QtWidgets.QTableWidgetItem("R$ 50,00"))  # Valor do produto

        # Criando um botão na coluna "Ação"
        button = QtWidgets.QPushButton("Adicionar à cesta")
        button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))  # Cursor de mão ao passar sobre o botão
        button.setStyleSheet("""
            QPushButton {
                background-color: rgb(0, 75, 63);
                font: 75 7pt "MS Shell Dlg 2";
                color: white; /* Cor do texto */
                border-radius: 8px; /* Bordas arredondadas */
                padding: 5px 10px; /* Padding interno */
            }
            QPushButton:hover {
                background-color: rgb(0, 100, 85);
            }
            QPushButton:pressed {
                background-color: rgb(0, 60, 50);
            }
        """)

        # Conectando o botão a uma ação diretamente com lambda
        button.clicked.connect(lambda: QtWidgets.QMessageBox.information(
            None, "DrogaLaugh", "Produto adicionado à cesta com sucesso!"
        ))

        # Adicionando o botão à célula da tabela
        self.tableWidget.setCellWidget(0, 3, button)  # Coluna "Ação"

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Produtos"))

        self.btnNomelogo.setWhatsThis(
                _translate("MainWindow", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.btnNomelogo.setText(_translate("MainWindow", "DrogaLaugh"))

        self.label_7.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#004b3f;\">Vizualize nossos produtos</span></p></body></html>"))


        self.botaoCesta.setWhatsThis(_translate("MainWindow", "<html><head/><body><p\n"
"                        align=\"right\"><br/></p></body></html>"))
        self.botaoCesta.setText(_translate("MainWindow", "CESTA"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">Sobre Nós</span></p></body></html>"))
        self.label_26.setText(_translate("MainWindow",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
                                         "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">A DrogaLaugh é sua farmácia de confiança, oferecendo</span></p>\n"
                                         "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\"> produtos de qualidade e atendimento excepcional </span></p>\n"
                                         "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">desde 2024.</span></p></body></html>"))

        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\n"
"                            font-weight:600;\n"
"                            color:#ffffff;\">Contatos</span></p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\"\n"
"                            \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"                            <html><head><meta name=\"qrichtext\" content=\"1\"\n"
"                            /><style type=\"text/css\">\n"
"                            p, li { white-space: pre-wrap; }\n"
"                            </style></head><body style=\" font-family:\'MS Shell Dlg 2\';\n"
"                            font-size:8pt; font-weight:400; font-style:normal;\">\n"
"                            <p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px;\n"
"                            -qt-block-indent:0; text-indent:0px;\"><span style=\"\n"
"                            color:#ffffff;\">0800 123 4567</span></p>\n"
"                            <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\n"
"                            -qt-block-indent:0; text-indent:0px;\"><span style=\"\n"
"                            color:#ffffff;\">contato@drogalaugh.com</span></p>\n"
"                            <p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\n"
"                            -qt-block-indent:0; text-indent:0px;\"><span style=\"\n"
"                            color:#ffffff;\">Junco, 123</span></p>\n"
"                            <p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px;\n"
"                            -qt-block-indent:0; text-indent:0px;\"><span style=\"\n"
"                            color:#ffffff;\">Picos - PI</span></p></body></html>"))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\n"
"                            font-weight:600; color:#ffffff;\">Redes\n"
"                            Sociais</span></p></body></html>"))
        self.label_30.setText(_translate(
                "MainWindow",
                "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                "p { white-space: nowrap; margin: 5px 0; display: flex; align-items: center; }\n"
                "img { margin-right: 8px; vertical-align: center; }\n"
                "span { font-size: 12px; color: #ffffff; }\n"
                "</style></head>\n"
                "<body style=\" font-family:'MS Shell Dlg 2'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
                "<p><img src=\":/images/images/instagram.png\" height=\"16\" width=\"16\" /><span> @droga_laugh</span></p>\n"
                "<p><img src=\":/images/images/facebook.png\" height=\"16\" width=\"16\" /><span> Droga Laugh</span></p>\n"
                "</body></html>"
        ))
        self.botaoGerencia.setWhatsThis(
                _translate("MainWindow", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.botaoGerencia.setText(_translate("MainWindow", "GERENCIA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = TelaProdutosUi()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
