# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaBuscar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class TelaBuscaUi(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(931, 840)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnLogo = QtWidgets.QPushButton(self.centralwidget)
        self.btnLogo.setGeometry(QtCore.QRect(10, 0, 71, 71))
        self.btnLogo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnLogo.setStyleSheet("\n"
                                   "QPushButton {  \n"
                                   "    background-color: rgb(0, 75, 63);\n"
                                   "   font: 15pt \"Cooper Black\";\n"
                                   "    color: rgb(255, 255, 255); /* Cor do texto */\n"
                                   "    border-radius: 8px; /* Bordas arredondadas */\n"
                                   "    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
                                   "image:url(:/images/images/logofolha.png)\n"
                                   "    \n"
                                   "       \n"
                                   "}\n"
                                   "\n"
                                   "\n"
                                   "\n"
                                   "\n"
                                   "")
        self.btnLogo.setText("")
        self.btnLogo.setObjectName("btnLogo")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 931, 71))
        self.label_2.setStyleSheet("background-color: rgb(0, 75, 63);\n"
"\n"
"\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.labelBemvindo = QtWidgets.QLabel(self.centralwidget)
        self.labelBemvindo.setGeometry(QtCore.QRect(70, 80, 791, 161))
        self.labelBemvindo.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";\n"
"")
        self.labelBemvindo.setObjectName("labelBemvindo")
        self.LineBuscar = QtWidgets.QLineEdit(self.centralwidget)
        self.LineBuscar.setGeometry(QtCore.QRect(190, 240, 541, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.LineBuscar.setFont(font)
        self.LineBuscar.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.LineBuscar.setStyleSheet("QLineEdit {\n"
" border: 1px solid #CCCCCC;\n"
"border-radius: 8px;\n"
"padding: 5px;\n"
"}\n"
"\n"
"QLineEdit ::focus {\n"
"    background-color: rgb(0, 75, 63);\n"
"}")
        self.LineBuscar.setFrame(True)
        self.LineBuscar.setClearButtonEnabled(False)
        self.LineBuscar.setObjectName("LineBuscar")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 310, 311, 41))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0, 670, 931, 161))
        self.label_8.setStyleSheet("background-color: rgb(0, 75, 63);\n"
"\n"
"\n"
"")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")

        self.labelFrase = QtWidgets.QLabel(self.centralwidget)
        self.labelFrase.setGeometry(QtCore.QRect(310, 190, 301, 21))
        self.labelFrase.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color:#6E7683;")
        self.labelFrase.setObjectName("labelFrase")
        self.btnNomelogo = QtWidgets.QPushButton(self.centralwidget)
        self.btnNomelogo.setGeometry(QtCore.QRect(70, 10, 181, 51))
        self.btnNomelogo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNomelogo.setStyleSheet("\n"

                                       "QPushButton {  \n"
                                       "    background-color: rgb(0, 75, 63);\n"
                                       "   font: 15pt \"Cooper Black\";\n"
                                       "    color: rgb(255, 255, 255); /* Cor do texto */\n"
                                       "    border-radius: 8px; /* Bordas arredondadas */\n"
                                       "    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
                                       "    \n"
                                       "       \n"
                                       "}\n"
                                       "\n"
                                       "\n"
                                       "\n"
                                       "\n"
                                       "")
        self.btnNomelogo.setObjectName("btnNomelogo")
        self.botaoBuscar = QtWidgets.QPushButton(self.centralwidget)
        self.botaoBuscar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaoBuscar.setGeometry(QtCore.QRect(690, 240, 41, 41))
        self.botaoBuscar.setStyleSheet("QPushButton {  \n"
"    background-color: rgb(0, 75, 63);\n"
"     border-radius: 8px; /* Bordas arredondadas */\n"
"    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
"    image: url(:/images/images/lupa-arredondada.png); /* Caminho da imagem */\n"
"      \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  background-color: #E5E5E5;\n"
"   \n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
"    image: url(:/images/images/lupa-arredondada.png); /* Caminho da imagem */\n"
"    \n"
"border: 1px solid #CCCCCC;\n"
"box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); /* Sombra leve */\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #E5E5E5;\n"
"    \n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
"    image: url(:/images/images/lupa-arredondada.png); /* Caminho da imagem */\n"
"    \n"
"border: 1px solid #CCCCCC;\n"
"box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); /* Sombra leve */\n"
"background-color: #D6D6D6; /* Fundo mais escuro */\n"
"    box-shadow: 0px 2px 3px rgba(0, 0, 0, 0.2); /* Menor sombra */\n"
"    transform: translateY(2px); /* Deslocamento para baixo */\n"
"    border: 1px solid #AAAAAA; /* Borda mais escura */\n"
"}\n"
"\n"
"\n"
"")
        self.botaoBuscar.setText("")
        self.botaoBuscar.setObjectName("botaoBuscar")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 360, 161, 211))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setStyleSheet("background-color: white; ")
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 161, 121))
        self.label.setStyleSheet("image: url(:/images/images/medicina-natural.png);")

        self.label.setText("")
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 120, 131, 31))
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(10, 150, 101, 21))
        self.label_9.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 75, 63)")
        self.label_9.setObjectName("label_9")
        self.BotaoAddCesta = QtWidgets.QPushButton(self.frame)
        self.BotaoAddCesta.setGeometry(QtCore.QRect(30, 180, 101, 31))
        self.BotaoAddCesta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BotaoAddCesta.setStyleSheet("QPushButton {  \n"
"    background-color: rgb(0, 75, 63);\n"
"    font: 75 7pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255); /* Cor do texto */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
"    image: url(:/images/images/001-shopping-basket.png); /* Caminho da imagem */\n"
"    image-position:left;   \n"
"    text-align: right; /* Centraliza o texto */    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  background-color: #E5E5E5;\n"
"    font: 75 7pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255); /* Cor do texto */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
"    image: url(:/images/images/001-shopping-basket.png); /* Caminho da imagem */\n"
"    image-position:left;   \n"
"    text-align: right; /* Centraliza o texto */\n"
"border: 1px solid #CCCCCC;\n"
"box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); /* Sombra leve */\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #E5E5E5;\n"
"    font: 75 7pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255); /* Cor do texto */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
"    image: url(:/images/images/001-shopping-basket.png); /* Caminho da imagem */\n"
"    image-position:left;   \n"
"    text-align: right; /* Centraliza o texto */\n"
"border: 1px solid #CCCCCC;\n"
"box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); /* Sombra leve */\n"
"background-color: #D6D6D6; /* Fundo mais escuro */\n"
"    box-shadow: 0px 2px 3px rgba(0, 0, 0, 0.2); /* Menor sombra */\n"
"    transform: translateY(2px); /* Deslocamento para baixo */\n"
"    border: 1px solid #AAAAAA; /* Borda mais escura */\n"
"}\n"
"\n"
"\n"
"")
        self.BotaoAddCesta.setObjectName("BotaoAddCesta")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(210, 360, 161, 211))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setStyleSheet(
            "background-color: white; ")
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(10, 120, 131, 31))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(10, 150, 101, 21))
        self.label_13.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"color:rgb(0, 75, 63)")
        self.label_13.setObjectName("label_13")
        self.BotaoAddCesta_2 = QtWidgets.QPushButton(self.frame_2)
        self.BotaoAddCesta_2.setGeometry(QtCore.QRect(30, 180, 101, 31))
        self.BotaoAddCesta_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BotaoAddCesta_2.setStyleSheet("QPushButton {  \n"
"    background-color: rgb(0, 75, 63);\n"
"    font: 75 7pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255); /* Cor do texto */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
"    image: url(:/images/images/001-shopping-basket.png); /* Caminho da imagem */\n"
"    image-position:left;   \n"
"    text-align: right; /* Centraliza o texto */    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  background-color: #E5E5E5;\n"
"    font: 75 7pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255); /* Cor do texto */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
"    image: url(:/images/images/001-shopping-basket.png); /* Caminho da imagem */\n"
"    image-position:left;   \n"
"    text-align: right; /* Centraliza o texto */\n"
"border: 1px solid #CCCCCC;\n"
"box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); /* Sombra leve */\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #E5E5E5;\n"
"    font: 75 7pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255); /* Cor do texto */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
"    image: url(:/images/images/001-shopping-basket.png); /* Caminho da imagem */\n"
"    image-position:left;   \n"
"    text-align: right; /* Centraliza o texto */\n"
"border: 1px solid #CCCCCC;\n"
"box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); /* Sombra leve */\n"
"background-color: #D6D6D6; /* Fundo mais escuro */\n"
"    box-shadow: 0px 2px 3px rgba(0, 0, 0, 0.2); /* Menor sombra */\n"
"    transform: translateY(2px); /* Deslocamento para baixo */\n"
"    border: 1px solid #AAAAAA; /* Borda mais escura */\n"
"}\n"
"\n"
"\n"
"")
        self.BotaoAddCesta_2.setObjectName("BotaoAddCesta_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 161, 121))
        self.label_4.setStyleSheet("image: url(:/images/images/drogas.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.BotaoAddCesta_2.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.botaoCesta = QtWidgets.QPushButton(self.centralwidget)
        self.botaoCesta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaoCesta.setGeometry(QtCore.QRect(670, 20, 91, 38))
        self.botaoCesta.setStyleSheet("QPushButton {  \n"
"    background-color: rgb(0, 75, 63);\n"
"    font: 75 9pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255); /* Cor do texto */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
"    image: url(:/images/images/001-shopping-basket.png); /* Caminho da imagem */\n"
"    image-position:left;   \n"
"    text-align: right; /* Centraliza o texto */    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  background-color: #E5E5E5;\n"
"    font: 75 9pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255); /* Cor do texto */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
"    image: url(:/images/images/001-shopping-basket.png); /* Caminho da imagem */\n"
"    image-position:left;   \n"
"    text-align: right; /* Centraliza o texto */\n"
"border: 1px solid #CCCCCC;\n"
"box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); /* Sombra leve */\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #E5E5E5;\n"
"    font: 75 9pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255); /* Cor do texto */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
"    image: url(:/images/images/001-shopping-basket.png); /* Caminho da imagem */\n"
"    image-position:left;   \n"
"    text-align: right; /* Centraliza o texto */\n"
"border: 1px solid #CCCCCC;\n"
"box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); /* Sombra leve */\n"
"background-color: #D6D6D6; /* Fundo mais escuro */\n"
"    box-shadow: 0px 2px 3px rgba(0, 0, 0, 0.2); /* Menor sombra */\n"
"    transform: translateY(2px); /* Deslocamento para baixo */\n"
"    border: 1px solid #AAAAAA; /* Borda mais escura */\n"
"}\n"
"\n"
"\n"
"")
        self.botaoCesta.setObjectName("botaoCesta")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(20, 680, 321, 131))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_25 = QtWidgets.QLabel(self.frame_5)
        self.label_25.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_5)
        self.label_26.setGeometry(QtCore.QRect(10, 30, 301, 91))
        self.label_26.setObjectName("label_26")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(420, 680, 181, 131))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_27 = QtWidgets.QLabel(self.frame_6)
        self.label_27.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame_6)
        self.label_28.setGeometry(QtCore.QRect(10, 30, 301, 91))
        self.label_28.setObjectName("label_28")
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(710, 680, 171, 131))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_29 = QtWidgets.QLabel(self.frame_7)
        self.label_29.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame_7)
        self.label_30.setGeometry(QtCore.QRect(10, 20, 301, 91))
        self.label_30.setObjectName("label_30")
        self.botaoGerencia = QtWidgets.QPushButton(self.centralwidget)
        self.botaoGerencia.setCursor((QtGui.QCursor(QtCore.Qt.PointingHandCursor)))
        self.botaoGerencia.setGeometry(QtCore.QRect(780, 20, 111, 38))
        self.botaoGerencia.setStyleSheet("QPushButton {  \n"
                                         "    \n"
                                         "    background-color: rgb(0, 75, 63);\n"
                                         "    font: 75 9pt \"MS Shell Dlg 2\";\n"
                                         "    color: rgb(255, 255, 255); /* Cor do texto */\n"
                                         "    border-radius: 8px; /* Bordas arredondadas */\n"
                                         "    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
                                         "   image: url(:/images/images/gerenciamento-de-projetos.png); /* Caminho da imagem */\n"
                                         "    image-position:left;   \n"
                                         "    text-align: right; /* Centraliza o texto */    \n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:hover{\n"
                                         "  background-color: #E5E5E5;\n"
                                         "    font: 75 9pt \"MS Shell Dlg 2\";\n"
                                         "    color: rgb(255, 255, 255); /* Cor do texto */\n"
                                         "    border-radius: 8px; /* Bordas arredondadas */\n"
                                         "    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
                                         "   image: url(:/images/images/gerenciamento-de-projetos.png); /* Caminho da imagem */\n"
                                         "    image-position:left;   \n"
                                         "    text-align: right; /* Centraliza o texto */\n"
                                         "border: 1px solid #CCCCCC;\n"
                                         "box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); /* Sombra leve */\n"
                                         "}\n"
                                         "QPushButton:pressed{\n"
                                         "background-color: #E5E5E5;\n"
                                         "    font: 75 9pt \"MS Shell Dlg 2\";\n"
                                         "    color: rgb(255, 255, 255); /* Cor do texto */\n"
                                         "    border-radius: 8px; /* Bordas arredondadas */\n"
                                         "    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
                                         "  image: url(:/images/images/gerenciamento-de-projetos.png); /* Caminho da imagem */\n"
                                         "    image-position:left;   \n"
                                         "    text-align: right; /* Centraliza o texto */\n"
                                         "border: 1px solid #CCCCCC;\n"
                                         "box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); /* Sombra leve */\n"
                                         "background-color: #D6D6D6; /* Fundo mais escuro */\n"
                                         "    box-shadow: 0px 2px 3px rgba(0, 0, 0, 0.2); /* Menor sombra */\n"
                                         "    transform: translateY(2px); /* Deslocamento para baixo */\n"
                                         "    border: 1px solid #AAAAAA; /* Borda mais escura */\n"
                                         "}\n"
                                         "\n"
                                         "\n"
                                         "")
        self.botaoGerencia.setObjectName("botaoGerencia")
        self.botaoBuscar_2 = QtWidgets.QPushButton(self.centralwidget)
        self.botaoBuscar_2.setGeometry(QtCore.QRect(850, 390, 71, 81))
        self.botaoBuscar_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaoBuscar_2.setStyleSheet("QPushButton {  \n"
"   \n"
"     border-radius: 8px; /* Bordas arredondadas */\n"
"    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
"  image: url(:/images/images/seta-direita.png);\n"
"      \n"
"}\n"
"\n"

"\n"
"")
        self.botaoBuscar_2.setText("")
        self.botaoBuscar_2.setObjectName("botaoBuscar_2")

        self.label_8.raise_()
        self.frame.raise_()
        self.label_2.raise_()
        self.labelBemvindo.raise_()
        self.LineBuscar.raise_()
        self.label_7.raise_()
        self.labelFrase.raise_()
        self.btnLogo.raise_()
        self.btnNomelogo.raise_()
        self.botaoBuscar.raise_()
        self.frame_2.raise_()
        self.botaoCesta.raise_()
        self.frame_5.raise_()
        self.frame_6.raise_()
        self.frame_7.raise_()
        self.botaoGerencia.raise_()
        self.botaoBuscar_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Buscar Produto"))
        icon = QtGui.QIcon(":/images/images/logofolha.png")  # Caminho para sua imagem de logo
        MainWindow.setWindowIcon(icon)
        self.labelBemvindo.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.labelBemvindo.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18pt; font-weight:72; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#004b3f;\">DROGALAUGH!</span></p></body></html>"))
        self.LineBuscar.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/images/images/lupa.png\"/></p></body></html>"))
        self.LineBuscar.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><img src=\":/images/images/lupa.png\"/></p></body></html>"))
        self.LineBuscar.setPlaceholderText(_translate("MainWindow", "O que você está procurando?"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#004b3f;\">Resultados da busca por: </span><span style=\" font-size:10pt; color:#004b3f;\">Vitamina C</span></p></body></html>"))
        self.labelFrase.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:400;\">Cuidando da sua saúde com dedicação!</span></p></body></html>"))
        self.btnNomelogo.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.btnNomelogo.setText(_translate("MainWindow", "DrogaLaugh"))
        self.botaoBuscar.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Vitamina C 1000mg</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">R$ 76.42 </span></p></body></html>"))
        self.BotaoAddCesta.setText(_translate("MainWindow", "ADICIONAR"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Vitamina C 100mg</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">R$ 55,59</span></p></body></html>"))
        self.BotaoAddCesta_2.setText(_translate("MainWindow", "ADICIONAR"))
        self.botaoCesta.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        # self.botaoCesta.setText(_translate("MainWindow", "R$0,00"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">Sobre Nós</span></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">A DrogaLaugh é sua farmácia de confiança, oferecendo</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\"> produtos de qualidade e atendimento excepcional </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">desde 2024.</span></p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">Contatos</span></p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">0800 123 4567</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">contato@drogalaugh.com</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Junco, 123</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Picos - PI</span></p></body></html>"))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">Redes Sociais</span></p></body></html>"))
        self.label_30.setText(_translate(
                "MainWindow",
                "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                "p { white-space: nowrap; margin: 5px 0; display: flex; align-items: center; }\n"
                "img { margin-right: 8px; vertical-align: center; }\n"
                "span { font-size: 12px; color: #ffffff; }\n"
                "</style></head>\n"
                "<body style=\" font-family:'MS Shell Dlg 2'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
                "<p><img src=\":/images/images/instagram.png\" height=\"16\" width=\"16\" /><span> @droga_laugh</span></p>\n"
                "<p><img src=\":/images/images/facebook.png\" height=\"16\" width=\"16\" /><span> Droga Laugh</span></p>\n"
                "</body></html>"
        ))

        self.botaoGerencia.setWhatsThis(
                _translate("MainWindow", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.botaoGerencia.setText(_translate("MainWindow", "GERENCIA"))
        self.botaoBuscar_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = TelaBuscaUi()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
