# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaCestaVazia.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(931, 840)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setGeometry(QtCore.QRect(560, 10, 351, 791))
        self.frame_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 15px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label = QtWidgets.QLabel(self.frame_8)
        self.label.setGeometry(QtCore.QRect(90, 240, 181, 181))
        self.label.setStyleSheet("image: url(:/images/images/compras.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame_8)
        self.label_3.setGeometry(QtCore.QRect(80, 410, 241, 41))
        self.label_3.setStyleSheet("font: 75 13pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        self.label_2.setGeometry(QtCore.QRect(90, 450, 181, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.botaoIrparaOfertas = QtWidgets.QPushButton(self.frame_8)
        self.botaoIrparaOfertas.setGeometry(QtCore.QRect(100, 500, 151, 38))
        self.botaoIrparaOfertas.setStyleSheet("QPushButton {  \n"
"    background-color: rgb(0, 75, 63);\n"
"    font: 75 9pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255); /* Cor do texto */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
"  \n"
"    image-position:left;   \n"
"    text-align: right; /* Centraliza o texto */    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"  background-color: #E5E5E5;\n"
"    font: 75 9pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255); /* Cor do texto */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
"    \n"
"    image-position:left;   \n"
"    text-align: right; /* Centraliza o texto */\n"
"border: 1px solid #CCCCCC;\n"
"box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); /* Sombra leve */\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #E5E5E5;\n"
"    font: 75 9pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255); /* Cor do texto */\n"
"    border-radius: 8px; /* Bordas arredondadas */\n"
"    padding: 10px; /* Padding interno (topo, direita, fundo, esquerda) */\n"
"    \n"
"    image-position:left;   \n"
"    text-align: right; /* Centraliza o texto */\n"
"border: 1px solid #CCCCCC;\n"
"box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.1); /* Sombra leve */\n"
"background-color: #D6D6D6; /* Fundo mais escuro */\n"
"    box-shadow: 0px 2px 3px rgba(0, 0, 0, 0.2); /* Menor sombra */\n"
"    transform: translateY(2px); /* Deslocamento para baixo */\n"
"    border: 1px solid #AAAAAA; /* Borda mais escura */\n"
"}\n"
"\n"
"\n"
"")
        self.botaoIrparaOfertas.setObjectName("botaoIrparaOfertas")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cesta de Produtos"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400; color:#000000;\">Sua cesta está vazia</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#004b3f;\">Confira nossas ofertas!</span></p></body></html>"))
        self.botaoIrparaOfertas.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.botaoIrparaOfertas.setText(_translate("MainWindow", "IR PARA OFERTAS"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
